version: "3.9"  # optional since v1.27.0
services:
  typo3:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 8000:80
    extra_hosts:
      - repository.127.0.0.1.xip.io:host-gateway
  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=typo3
      - MYSQL_PASSWORD=typo3
      - MYSQL_USER=typo3
      - MYSQL_DATABASE=typo3 
    command: 
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci